// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package soc.data;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Structs here are suffixed "Data" since we eventually want them used in the java code. Many struct names will then get
   *the same name as its OO counterparts. As in Java OO is central, I choose to suffix the data.
   * </pre>
   *
   * Protobuf enum {@code ResourceType}
   */
  public enum ResourceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * For now, we're still tied to the integer values. Therefore I want the values to be the same as we currently use
     * them until the integer dependencies are refactored out.
     * </pre>
     *
     * <code>NOT_YET_USED = 0;</code>
     */
    NOT_YET_USED(0),
    /**
     * <code>CLAY = 1;</code>
     */
    CLAY(1),
    /**
     * <code>ORE = 2;</code>
     */
    ORE(2),
    /**
     * <code>SHEEP = 3;</code>
     */
    SHEEP(3),
    /**
     * <code>WOOD = 4;</code>
     */
    WOOD(4),
    /**
     * <code>WHEAT = 5;</code>
     */
    WHEAT(5),
    /**
     * <code>GOLD_LOCAL = 6;</code>
     */
    GOLD_LOCAL(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * For now, we're still tied to the integer values. Therefore I want the values to be the same as we currently use
     * them until the integer dependencies are refactored out.
     * </pre>
     *
     * <code>NOT_YET_USED = 0;</code>
     */
    public static final int NOT_YET_USED_VALUE = 0;
    /**
     * <code>CLAY = 1;</code>
     */
    public static final int CLAY_VALUE = 1;
    /**
     * <code>ORE = 2;</code>
     */
    public static final int ORE_VALUE = 2;
    /**
     * <code>SHEEP = 3;</code>
     */
    public static final int SHEEP_VALUE = 3;
    /**
     * <code>WOOD = 4;</code>
     */
    public static final int WOOD_VALUE = 4;
    /**
     * <code>WHEAT = 5;</code>
     */
    public static final int WHEAT_VALUE = 5;
    /**
     * <code>GOLD_LOCAL = 6;</code>
     */
    public static final int GOLD_LOCAL_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResourceType valueOf(int value) {
      return forNumber(value);
    }

    public static ResourceType forNumber(int value) {
      switch (value) {
        case 0: return NOT_YET_USED;
        case 1: return CLAY;
        case 2: return ORE;
        case 3: return SHEEP;
        case 4: return WOOD;
        case 5: return WHEAT;
        case 6: return GOLD_LOCAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResourceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResourceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResourceType>() {
            public ResourceType findValueByNumber(int number) {
              return ResourceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return soc.data.Data.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResourceType[] VALUES = values();

    public static ResourceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResourceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResourceType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto*c\n\014ResourceType\022\020\n\014NOT_YET_" +
      "USED\020\000\022\010\n\004CLAY\020\001\022\007\n\003ORE\020\002\022\t\n\005SHEEP\020\003\022\010\n\004" +
      "WOOD\020\004\022\t\n\005WHEAT\020\005\022\016\n\nGOLD_LOCAL\020\006B\n\n\010soc" +
      ".datab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
